### ISSUE TITLE
[META] Fix remaining automated tests

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/feeds#127]
There's a lot to do:

- [ ]  Example: Node import (FeedsExamplesNodeTestCase)
- [ ]  Example: User import (FeedsExamplesUserTestCase)
- [ ]  Example: Node import (FeedsExamplesNodeTestCase)
- [ ]  Example: User import (FeedsExamplesUserTestCase)
- [ ]  ParserCSVTest (ParserCSVTest)
- [ ]  FeedsMapperFileTestCase (FeedsMapperFileTestCase)
- [ ]  FeedsCSVtoUsersTest (FeedsCSVtoUsersTest)
- [ ]  FeedsSitemapParserTestCase (FeedsSitemapParserTestCase)
- [ ]  FeedsFileHTTPTestCase (FeedsFileHTTPTestCase)
- [ ]  FeedsMapperFieldTestCase (FeedsMapperFieldTestCase)
- [ ]  FeedsMapperMultilingualFieldsTestCase (FeedsMapperMultilingualFieldsTestCase)
- [ ]  FeedsMapperListTestCase (FeedsMapperListTestCase)
- [ ]  FeedsMapperDateTestCase (FeedsMapperDateTestCase)
- [ ]  Feedsi18nNodeTestCase (Feedsi18nNodeTestCase)
- [ ]  Feedsi18nTaxonomyTestCase (Feedsi18nTaxonomyTestCase)
- [ ]  FeedsSchedulerTestCase (FeedsSchedulerTestCase)
- [ ]  Feeds account switcher test (FeedsAccountSwitcherTest)
- [ ]  FeedsEnclosure class test (FeedsEnclosureTest)
- [ ]  FeedsSource class test (FeedsSourceTest)
- [ ]  FeedsCSVtoTermsTest (FeedsCSVtoTermsTest)
- [ ]  FeedsFetcherResult class test (FeedsFetcherResultTest)
- [ ]  FeedsMapperProfileTestCase (FeedsMapperProfileTestCase)
- [ ]  FeedsHTTPCache class test (FeedsHTTPCacheTest)
- [ ]  FeedsMapperTaxonomyTestCase (FeedsMapperTaxonomyTestCase)
- [ ]  FeedsMapperLinkTestCase (FeedsMapperLinkTestCase)
- [ ]  FeedsMapperDateMultipleTestCase (FeedsMapperDateMultipleTestCase)
- [ ]  FeedsMapperPathTestCase (FeedsMapperPathTestCase)
- [ ]  FeedsMapperPathPathautoTestCase (FeedsMapperPathPathautoTestCase)
- [ ]  FeedsSyndicationParserTestCase (FeedsSyndicationParserTestCase)
- [ ]  FeedsPushTest (FeedsPushTest)
- [ ]  FeedsRSStoNodesTest (FeedsRSStoNodesTest)
- [ ]  FeedsMapperFormatConfig (FeedsMapperFormatConfig)
- [ ]  FeedsMapperNodeSummaryTestCase (FeedsMapperNodeSummaryTestCase)
- [ ]  Feed content type (FeedsContentTypeTest)

Pick one, open a separate issue for your pull request and link that issue here in this meta. Once fixed, mark it here.

**Comment by indigoxela** [comment]
There are some tests that require these additional modules:

- rules
- og
- profile
- i18n
- feeds_xpathparser (now added)

Does it make sense to always checkout all of them for test runs? Not sure.

**Comment by indigoxela** [comment]
Another [PR](https://github.com/backdrop-contrib/feeds/pull/128) that affects many tests is available. There are some drive-by fixes and a lot less exceptions thrown.

Now somebody else may take over - as the issue description suggests. :wink:
